### ISSUE TITLE
[Request] Moleculer Laboratory

### ISSUE THREAD

**Issue by AndreMaz** [moleculerjs/educational-content#1]
## Structure

- Title  :arrow_right: **Example:** *Moleculer Laboratory - All-in-one development dashboard*

- Introduction  :arrow_right: **Example:** *Explain why it's important for a developer to use Moleculer Laboratory during the development of a microservices-based web application*

- Goals :arrow_right: **Example:** Explain what does the dev gain by using Moleculer Laboratory. For example: *faster development*

- Prerequisites :arrow_right: **Example:** *Mention that the reader must know about distributed apps and it need Moleculer v0.14 installed*

- Step-by-step instructions :arrow_right: **Example:**  *Do this... Then, do that... Finally, open your browser and...*

- Provide a link to the source code of your article/tutorial :arrow_right: **Example:** *https://github.com/myName/awesome_tutorial* 

- Conclusion :arrow_right: **Example:** *After reading this article/tutorial you've become a better developer because...*

**Comment by brasiqui** [comment]
I'm interested in this topic.

**Comment by icebob** [comment]
@brasiqui you are right, something is wrong with events. I'm trying fixing it...

**Comment by icebob** [comment]
I've fixed. Press CTRL+F5 and it will work.

**Comment by brasiqui** [comment]
Hi, this is a first version of the article.
Like you, my first language is not english, so maybe there are some mistakes.
Any idea is welcome.

https://medium.com/@ronidacruz/moleculers-laboratory-b3262cc3b39e

Obrigado!

**Comment by icebob** [comment]
Good job, I wrote some notes.

**Comment by brasiqui** [comment]
> Good job, I wrote some notes.

Hi, I finished the corrections and add the repository.

Thanks

**Comment by icebob** [comment]
Great, @AndreMaz please review you, too.

**Comment by icebob** [comment]
@brasiqui please fix this part, it's a little ugly:
![image](https://user-images.githubusercontent.com/306521/139727918-dc7f7946-bb4b-4d03-81b5-7b4acb7c2fca.png)

**Comment by brasiqui** [comment]
Fixed.
Is the code properly formatted? In my preview the text is not selectable.
Maybe it will be correct after publish.
If it's not okay I can use GitHub Gist. But I like the current colors.

**Comment by brasiqui** [comment]
I'm thinking about how to improve the intro part to produce more appeal...

**Comment by icebob** [comment]
Text selecting works for me:
![LCIT93JTxR](https://user-images.githubusercontent.com/306521/139905276-c525273e-3dd3-426f-b628-455852247ba1.gif)

**Comment by AndreMaz** [comment]
> Great, @AndreMaz please review you, too.

Sure thing, give me a couple of hours

**Comment by AndreMaz** [comment]
Hey @brasiqui I've reviewed and left some comments. Overall it's all good 👍. I just improved some sentences and offer some suggestions.

Regarding the introduction. I really like your idea but I think it's a little bit raw. What do you think about replacing first 3 paragraphs with something like this

> The development of a microservices-based application involves multiple moving parts. It’s a process of designing/creating complex interactions between several services. As the application grows in complexity it becomes hard to create a mental picture of service relations and their interactions, which inevitably slows the development and the debugging. A tool that can provide a graphical overview of the system and track the interactions between the services can greatly alleviate the cognitive load of the developer and, therefore, result in a significant speed-up during the application development.

> Moleculer Lab is a dashboard designed to solve the abovementioned issues during the during the development of a Moleculer-based application. The dashboard includes global architecture overview, system load, services calls, event listener and much more.

**Comment by icebob** [comment]
@brasiqui please try to move the Draft into Moleculer publications. Currently, I didn't see André's comments

**Comment by brasiqui** [comment]
Hi @AndreMaz , I totally agree.
Corrections made.

**Comment by brasiqui** [comment]
I moved to "Submitted to publication".

**Comment by icebob** [comment]
Cool, we see it and we can publish. I think we will publish it next week. Please send a DM on Discord to me.

**Comment by icebob** [comment]
The article has been published 👍 
https://medium.com/moleculer/moleculers-laboratory-b3262cc3b39e
